version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postresql/data/.gameday
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5434:5432
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-net:
    driver: bridge
